spring: 
   profiles:
     active: instance1
   application:
     name: gateway
   datasource:
     username: root
     password: oyh1203oy
     url: jdbc:mysql://localhost:3306/bms_gateway?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
     driver-class-name: com.mysql.jdbc.Driver
   redis:
     #Redis服务器地址  
     host: 127.0.0.1
     #Redis服务器端口
     port: 6379
     #Redis服务器密码
     requirePass: oyh1203
         #超时时间
     timeout: 3000
     pool:
             # 连接池最大连接数（使用负值表示没有限制） 
       max-active: 100
             #连接池最大阻塞等待时间（使用负值表示没有限制）
       max-wait: 300000
            # 连接池中的最大空闲连接 
       max-idle: 10
            # 连接池中的最小空闲连接 
       min-idle: 0
   cloud:
     gateway:
       discovery:
         locator:
           #\u662F\u5426\u548C\u670D\u52A1\u6CE8\u518C\u4E0E\u53D1\u73B0\u7EC4\u4EF6\u7ED3\u5408\uFF0C\u8BBE\u7F6E\u4E3A true \u540E\u53EF\u4EE5\u76F4\u63A5\u4F7F\u7528\u5E94\u7528\u540D\u79F0\u8C03\u7528\u670D\u52A1
           enabled: true
           #\u5C06\u670D\u52A1\u540D\u79F0\u8F6C\u6362\u4E3A\u5C0F\u5199
           lower-case-service-id: true
       default-filters:
         - name: Hystrix
           args:
             name : default
             fallbackUri: 'forward:/defaultFallback'
       routes:
         - id: annual-service
           uri: lb://ANNUAL
           predicates:
             - Path=/annual_service/annual/**
           filters:
             #截取路径位数
             - StripPrefix=1
         - id: daily-service
           uri: lb://DAILY
           predicates:
             #转发地址格式为/daily_service/daily/**,/daily_service部分会被下面的过滤器给截取掉
             - Path=/daily_service/daily/**
           filters:
             #截取路径位数
             - StripPrefix=1
         - id: oauth2-service
           uri: lb://OAUTH2
           predicates:
             #转发地址格式为/oauth_service/oauth/**,/oauth_service部分会被下面的过滤器给截取掉
             - Path=/oauth_service/oauth/**
           filters:
             #截取路径位数
             - StripPrefix=1
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
security:
  user:
    name: ouyang
    password: ouyang
logging:
  config: classpath:log.xml
  level:
    org:
      springframework:
        cloud:
          gateway: TRACE
    #showSql
    com:
      pccw:
        kernel:
          bmsGateway:
            mapper: debug
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 60000
mybatis:
  mapper-locations: classpath:mapper/*.xml 
#启用监控
management:
  endpoints:
    web:
      exposure:
        include: 
        - "*"  # 开放所有端点health，info，metrics，通过actuator/+端点名就可以获取相应的信息。默认打开health和info
  endpoint:
    health:
      show-details: always  #未开启actuator/health时，我们获取到的信息是{"status":"UP"}，status的值还有可能是 DOWN。开启后打印详细信息